spring.application.name=DutyServices

server.port=${SERVER_PORT:9004}

spring.data.mongodb.uri=mongodb+srv://brinda_22:Brinda22@cluster0.spfgdyh.mongodb.net/dutydb?retryWrites=true&w=majority&appName=Cluster0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.main.allow-bean-definition-overriding=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always